sudo: required
services:
    - docker

before-install:
    - docker build -f Dockerfile.dev -t fchwpo/docker-react . 

script:
    - docker run -e CI=true fchwpo/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react-new"
    env: "DockerReactNew-env"
    bucket_name: "elasticbeanstalk-us-east-1-547273590547"
    bucket_path: "docker-react-new"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY