FROM node:alpine AS builder
WORKDIR '/app'
COPY ./package.json .
RUN npm i --silent
COPY . . 
CMD ["npm", "run", "build"]


FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html

# WE CAN HAVE MULTIPLE PAHASES IN DOCKER BUILD PROCESS
# AFTER NEW PHASE PREVIOUS PHASE IS DISCARDED
# BUT THEIR OUTPUT CAN BE ACCESED
# SO IN THIS CASE OUR FINAL IMAGE WONT CONSIST OF NODE:ALPINE IT
# WILL ONLY CONSISTS OF NGINX
# BUT WE ARE USING BUILD OUTPUT OF BUILD_PAHASE TO NGINX